# Generated by Django 3.1.2 on 2021-11-08 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bowling_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512, null=True)),
                ('age', models.CharField(max_length=512, null=True)),
                ('country', models.CharField(max_length=512, null=True)),
                ('gender', models.CharField(max_length=512, null=True)),
                ('city', models.CharField(max_length=512, null=True)),
                ('state', models.CharField(max_length=512, null=True)),
                ('debut', models.CharField(max_length=512, null=True)),
                ('bowls', models.CharField(max_length=512, null=True)),
                ('events', models.CharField(max_length=512, null=True)),
                ('championships', models.CharField(max_length=512, null=True)),
                ('matches', models.CharField(max_length=512, null=True)),
                ('cashes', models.CharField(max_length=512, null=True)),
                ('titles', models.CharField(max_length=512, null=True)),
                ('average', models.CharField(max_length=512, null=True)),
            ],
        ),
    ]
