# Generated by Django 3.1.2 on 2020-10-11 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='music_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track', models.CharField(max_length=512)),
                ('album', models.CharField(max_length=512)),
                ('artist', models.CharField(max_length=512)),
                ('codes', models.CharField(max_length=512)),
                ('sesac', models.CharField(max_length=512)),
            ],
        ),
    ]
